#!/bin/sh
set -eu
FIXTURE_BASE64='GkXfo6NChoEBQveBAULygQRC84EIQoKIbWF0cm9za2FCh4EEQoWBAhhTgGcB/////////xFNm3Sxv4QckYMvTbuLU6uEFUmpZlOsgaFNu4tTq4QWVK5rU6yBwU27jFOrhBJUw2dTrIIBQuwBAAAAAAAAYgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFUmpZpu/hBr137Aq17GDD0JATYCETGF2ZldBhExhdmYWVK5r/L+Edcgzw64BAAAAAAAAbdeBAXPFiAAAAAAAAAABnIEAIrWcg3VuZIiBAIaGVl9GRlYxg4EBI+ODhDuaygDgkLCBELqBEJqBAlWwhFW5gQFjoqpWK4TRnAUvQTxgJulcN29dG3aXnTrJxCBDHoufVSBRL074oWg7mxcTfAMSVMNnsL+EI+p/cnNzp2PAi2PFiAAAAAAAAAABZ8iWRaOHRU5DT0RFUkSHiUxhdmMgZmZ2MR9DtnXvv4TUXHt354EAo+SBAACA/BWAANK+f//AAekqf5++/wAAEACkDLf2Pd6AANK+f//AAekqf5++/wAAEAAYLR0znByTANK+f//AAekqf5++/wAAEADiblSGEL89ANK+f//AAekqf5++/wAAEABCX25c'
emit() { printf '%s' "$FIXTURE_BASE64" | base64 -d; exit 0; }
trap emit TERM
INPUT=$(printf '%s' "${PUNCH_INPUT_BASE64:?}" | base64 -d)
WINDOW_SECONDS=$(printf '%s' "$INPUT" | sed -n 's/^{"nonce":"[0-9a-f]\{64\}","window_seconds":\([1-9][0-9]*\)}$/\1/p')
[ -n "$WINDOW_SECONDS" ] && [ "$WINDOW_SECONDS" -le 86400 ]
sleep "$WINDOW_SECONDS" & wait "$!"
emit
